# Generated by Django 5.2.14 on 2026-05-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_type', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('flag', models.CharField(max_length=10)),
                ('src_bytes', models.FloatField()),
                ('dst_bytes', models.FloatField()),
                ('predicted_label', models.IntegerField()),
                ('predicted_class', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
